### ISSUE TITLE
Search does not support UTF8 responses

### ISSUE THREAD

**Issue by dmckami** [spase-group/registry-services#2]
When accessing the 'search' endpoint of the spase-registry to search all entries that contain certain words, e.g.:
http://myspaseregistry.com/search?words=helloworld
the returned results will contain question marks where ever UTF8 symbols occur. Usually this is in the description field of the returned data set. When doing a 'resolver' request on that particular data set, the UTF8 symbols are returned as they should.

Looking into the code of Resolver.java and Search.java, I believe the problem is the contentType of the response:
Resolver.java (line 429): response.setContentType("text/xml; charset=UTF-8");
Search.java (line 323): response.setContentType("text/xml");

I didn't test these changes as I am lacking the build environment, so I only had a quick look through the code. I hope that helps.

I had another look at it with a fresh mind and I think two things might be important:
1. the `response.setContentType("text/xml; charset=UTF-8");` needs to go before `mOut.setOut(response.getWriter());`
2. I found that the `InputStreamReader `might need to be initialised with `"UTF-8"` parameter. Compare [Resolver.java line 1230](https://github.com/spase-group/registry-services/blob/e58cc0357869647de268f3449dadb167c9fbefa4/src/org/spase/registry/server/Resolver.java#L1230) and [Search.java line 544](https://github.com/spase-group/registry-services/blob/e58cc0357869647de268f3449dadb167c9fbefa4/src/org/spase/registry/server/Search.java#L544)

**Comment by tressahelvey** [comment]
Lee and Tressa reviewed and feel the issue has been resolved. Closing ticket.
